---
apiVersion: v1
kind: Service
metadata:
  name: kube-app
spec:
  selector:
      pod: kube-app
  ports:
    - port: 30002       # The port, the service listens on.
      targetPort: 8080  # The port, the traffic is sent to on the Pod.
  type: LoadBalancer
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-app
spec:
  replicas: 4
  selector:
    matchLabels:
      pod: kube-app
  template:
    metadata:
      labels:
        pod: kube-app
    spec:
      imagePullSecrets:
      - name: tanin.azurecr.io/kube-app
      containers:
        - name: kube-app
          image: tanin.azurecr.io/kube-app
          ports:
            - containerPort: 8080